---
# ðŸ“§ Gmail Transaction Search Configuration
# This file holds static data for the Gmail API script.

email_search:

  # List of official transaction sender emails
  senders:
    - "alerts@capitalone.com"
    - "online.banking@pnc.com"
    - "auto-confirm@amazon.com"
